# Generated by Django 4.1.7 on 2023-03-24 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_data', '0009_remove_recipe_likes_recipe_downvotes_recipe_upvotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='is_approved',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
