# Generated by Django 4.1.7 on 2023-03-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_data', '0010_alter_recipe_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='is_approved',
            field=models.BooleanField(default='Uknown', null=True),
        ),
    ]
